"""fix customer id autoincrement

Revision ID: 6daaa2d10dae
Revises: b229f0a2aec9
Create Date: 2026-02-18 15:06:24.888441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6daaa2d10dae'
down_revision: Union[str, Sequence[str], None] = 'b229f0a2aec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
